Repository nautes-labs/website, pull requests merged in 2023-05, with the labels that each got.

#22 add description of the location of the destory environment log.
  src/en/guide/user-guide/installation.md
  src/guide/user-guide/installation.md
Labels: documentation

#15 add register-runtime-cluster in English
  src/en/guide/user-guide/cluster.md
  src/en/guide/user-guide/deploy-an-application.md
  src/guide/user-guide/cluster.md
  src/guide/user-guide/deploy-an-application.md
Labels: documentation

#16 add maintain-product in English
  src/en/guide/user-guide/product.md
  src/guide/user-guide/product.md
Labels: documentation

#26 add description for the submission rules in main-process
  src/en/guide/user-guide/main-process.md
  src/guide/user-guide/main-process.md
Labels: documentation

#23 fix words in deploy-an-application
  src/en/guide/user-guide/deploy-an-application.md
Labels: documentation

#17 Add maintain-project in English
  src/en/guide/user-guide/project.md
  src/guide/user-guide/project.md
Labels: documentation

#18 Add maintain-repository in English
  src/en/guide/user-guide/code-repo.md
  src/guide/user-guide/code-repo.md
Labels: documentation

#19 Add maintain-environment in English
  src/en/guide/user-guide/environment.md
  src/guide/user-guide/environment.md
Labels: documentation

#21 Add view-deployment-results in English
  src/en/guide/user-guide/deployment-results.md
  src/guide/user-guide/deployment-results.md
Labels: documentation

#20 Add maintain-deployment-runtime in English
  src/en/guide/user-guide/deployment-runtime.md
  src/guide/user-guide/deployment-runtime.md
Labels: documentation

#27 fix the steps of view deployment results.
  src/en/guide/user-guide/deployment-results.md
  src/guide/user-guide/deployment-results.md
Labels: documentation

#28 update entity-definition in-introduction.
  src/en/guide/user-guide/introduction.md
Labels: documentation

#30 Optimize the english statement of feature-2 in the overview
  src/en/guide/user-guide/introduction.md
  src/en/index.md
Labels: documentation

#31 fix words in deploy-an-app.
  src/en/guide/user-guide/deploy-an-application.md
  src/guide/user-guide/deploy-an-application.md
Labels: documentation

#36 Fixed some wording and formatting issues.
  src/en/guide/user-guide/code-repo.md
  src/en/guide/user-guide/deployment-results.md
  src/en/guide/user-guide/deployment-runtime.md
  src/en/guide/user-guide/environment.md
  src/en/guide/user-guide/product.md
  src/en/guide/user-guide/project.md
  src/guide/user-guide/code-repo.md
  src/guide/user-guide/deployment-results.md
  src/guide/user-guide/deployment-runtime.md
  src/guide/user-guide/environment.md
  src/guide/user-guide/product.md
  src/guide/user-guide/project.md
Labels: documentation

#39 Optimize API annotations and field definitions.
  src/api/tadmin/cluster.md
  src/api/user/projectpipelineruntime.md
  src/en/api/tadmin/cluster.md
  src/en/api/user/projectpipelineruntime.md
Labels: bug, documentation

#35 Optimize main process
  src/en/guide/images/user-guide-overview-1.png
  src/en/guide/user-guide/main-process.md
  src/guide/images/user-guide-overview-1.png
  src/guide/user-guide/main-process.md
Labels: documentation

#33 Optimize clean environment
  src/en/guide/user-guide/clean-environment.md
  src/guide/user-guide/clean-environment.md
Labels: documentation

#32 Feature run pipeline
  src/.vuepress/config.js
  src/guide/user-guide/run-a-pipeline.md
Labels: documentation

#34 Adjust the content of the document 'deploy an application' according …
  src/en/guide/user-guide/deploy-an-application.md
  src/guide/user-guide/deploy-an-application.md
Labels: documentation

#44 Add an empty English version of the run-a-pipeline
  src/en/guide/user-guide/run-a-pipeline.md
Labels: bug

#45 Fixed the release version of the CLI project.
  src/en/guide/user-guide/clean-environment.md
  src/en/guide/user-guide/deploy-an-application.md
  src/guide/user-guide/clean-environment.md
  src/guide/user-guide/deploy-an-application.md
  src/guide/user-guide/run-a-pipeline.md
Labels: bug, documentation

#46 Fixed run-a-pipeline doc header.
  src/en/guide/user-guide/run-a-pipeline.md
  src/guide/user-guide/run-a-pipeline.md
Labels: bug, documentation

#41 fix words issues in the maintain-product section.
  src/guide/user-guide/product.md
Labels: documentation

#47 fix words issues in the maintain-product section.
  src/en/guide/user-guide/product.md
Labels: documentation
